language: dart
dart: stable

jobs:
  include:
    - stage: analyze
      script: dartanalyzer --fatal-warnings .
    - stage: analyze
      script: dartfmt --dry-run --set-exit-if-changed .
    - stage: unit_test
      script: pub run test test/all_test.dart --platform vm
    - stage: coverage
      script:
        - pub global activate dart_coveralls
        - dart_coveralls report --debug --exclude-test-files --token=$COVERALLS_REPO_TOKEN test/all_test.dart
stages:
  - analyze
  - unit_test
  - coverage

sudo: required
cache:
  directories:
    - $HOME/.pub-cache
    - .dart_tool/build