name: maps_toolkit
description: Maps toolkit - geo-measurements utils - area of polygon, distance between point, heading and offset between points (port of SphericalUtil, PolyUtil from `android-maps-utils`).
version: 3.0.0
homepage: https://github.com/kb0/maps_toolkit/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: 2.1.1
  test: 1.24.6
